### ISSUE TITLE
Docker not compatible

### ISSUE THREAD

**Issue by waynevanson** [chunliu/typescript-react-hot-reload#6]
Hey there,

I thought it was a great idea to run this with docker, as per my usual development stack, which is not yielding a friendly result.

I'm very familiar with docker and this should work, but with hot reloading it looks like it won't output to a port

`yarn start` works without docker. When it's run in docker, it does not work.

Any ideas how to resolve? I think that it's got to do with `webpack.config.js`

Happy to contribute where I can.

`docker-compose.yml`
```
version: '3.7'

services:
  react:
    container_name: react
    image: node
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/:/home/node/app
    working_dir: /home/node/app
    command: yarn start
```
